### ISSUE TITLE
搭配ScrollView使用，弹性失效

### ISSUE THREAD

**Issue by asche910** [ausboyue/ReboundEffects#1]
对于要求滑动的页面来讲，通常要搭配一个ScrollView或NestedScrollView，我项目这里使用后好像效果并不理想。不知道是否是特例情况。

**Comment by ausboyue** [comment]
是的，这个项目目标是提供实现弹性思路的，如果考虑ScrollView的情况，需要进一步实现的。

**Comment by asche910** [comment]
好吧，不过还是非常感谢！
